-- Round batch: live streaming + per-region pricing + auto-generated
-- subtitles flag. Idempotent — IF NOT EXISTS throughout.

-- contentSubtitleTracks.autoGenerated — distinguishes orchestrator-
-- generated tracks (Whisper) from creator-uploaded ones.
ALTER TABLE "content_subtitle_tracks"
	ADD COLUMN IF NOT EXISTS "auto_generated" boolean DEFAULT false NOT NULL;

-- live_streams — foundation for live streaming. Status moves through
-- idle → ingest → live → ending → ended.
CREATE TABLE IF NOT EXISTS "live_streams" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"creator_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
	"title" varchar(255) NOT NULL,
	"description" text,
	"stream_key" text NOT NULL UNIQUE,
	"rtmp_ingest_url" text,
	"playback_url" text,
	"thumbnail_url" text,
	"status" varchar(20) DEFAULT 'idle' NOT NULL,
	"visibility" varchar(20) DEFAULT 'public' NOT NULL,
	"scheduled_start_at" timestamp,
	"started_at" timestamp,
	"ended_at" timestamp,
	"viewer_count" integer DEFAULT 0 NOT NULL,
	"viewer_count_peak" integer DEFAULT 0 NOT NULL,
	"recording_media_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "live_streams_creator_idx" ON "live_streams" ("creator_id", "created_at");
CREATE INDEX IF NOT EXISTS "live_streams_status_idx" ON "live_streams" ("status");

-- content_pricing — per-region PPV pricing override.
CREATE TABLE IF NOT EXISTS "content_pricing" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"content_id" text NOT NULL REFERENCES "media_library"("id") ON DELETE CASCADE,
	"region_code" varchar(2) NOT NULL,
	"price_cents" integer NOT NULL,
	"currency" varchar(3) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "content_pricing_content_region_idx" ON "content_pricing" ("content_id", "region_code");
