import { json, type RequestHandler } from '@sveltejs/kit';
import { db } from '$lib/db/drizzle';
import { mediaLibrary, contentSubtitleTracks } from '$lib/db/schema/sepharstudios';
import { and, eq } from 'drizzle-orm';
import { Role } from '$lib/constants';
import { runAi, tryParseJson } from '$lib/server/ai';

/**
 * POST /api/ai/suggest/chapters
 *
 * Body: { contentId }
 * Returns: { suggestions: [{ start, title }] } — up to 12 candidates.
 *
 * Reads the orchestrator-generated transcript (kind='captions' AND
 * autoGenerated=true is preferred; falls back to any auto-generated track,
 * then any track for the content). Parses VTT cues, samples them down to
 * a ~6k-char digest, and asks the AI for time-coded chapter breaks. The
 * UI lets the creator review + accept the suggestions before saving.
 */

interface Cue {
	startSec: number;
	text: string;
}

/** VTT parser: extracts cue timestamps + text. Tolerant of WEBVTT header,
 *  blank-line separators, and `NOTE`/`STYLE` blocks (which we skip). */
function parseVtt(vtt: string): Cue[] {
	const cues: Cue[] = [];
	const blocks = vtt.replace(/\r\n/g, '\n').split(/\n\n+/);
	for (const block of blocks) {
		const lines = block.split('\n').filter(Boolean);
		if (lines.length === 0) continue;
		if (lines[0] === 'WEBVTT' || lines[0].startsWith('NOTE') || lines[0].startsWith('STYLE')) continue;
		// First line MAY be a cue identifier; the timestamp line contains `-->`.
		const tsLine = lines.find((l) => l.includes('-->'));
		if (!tsLine) continue;
		const [startRaw] = tsLine.split('-->');
		const startSec = vttTimeToSeconds(startRaw.trim());
		if (Number.isNaN(startSec)) continue;
		const text = lines.slice(lines.indexOf(tsLine) + 1).join(' ').replace(/<[^>]+>/g, '').trim();
		if (!text) continue;
		cues.push({ startSec, text });
	}
	return cues;
}

function vttTimeToSeconds(ts: string): number {
	// Formats: HH:MM:SS.mmm  or  MM:SS.mmm
	const parts = ts.split(':');
	const sec = parseFloat(parts.pop() ?? '0');
	const min = parseInt(parts.pop() ?? '0', 10);
	const hr = parseInt(parts.pop() ?? '0', 10);
	return hr * 3600 + min * 60 + sec;
}

/** Sample cues to a manageable digest size. Take every Nth cue so we
 *  cover the full timeline rather than just the first few minutes. */
function digest(cues: Cue[], maxChars: number): string {
	if (cues.length === 0) return '';
	let stride = 1;
	while (cues.slice(0, 9999).filter((_, i) => i % stride === 0).reduce((acc, c) => acc + c.text.length + 12, 0) > maxChars) {
		stride += 1;
		if (stride > 50) break;
	}
	return cues
		.filter((_, i) => i % stride === 0)
		.map((c) => `[${Math.round(c.startSec)}s] ${c.text}`)
		.join('\n');
}

export const POST: RequestHandler = async ({ locals, request }) => {
	const session = await locals.auth.getSession();
	if (!session) return json({ error: 'Unauthorized' }, { status: 401 });
	if (![Role.CREATOR, Role.ADMIN].includes(session.user.role as Role)) {
		return json({ error: 'Forbidden' }, { status: 403 });
	}

	const body = await request.json().catch(() => ({})) as { contentId?: string };
	const contentId = body.contentId?.trim();
	if (!contentId) return json({ error: 'contentId is required' }, { status: 400 });

	// Verify creator owns this content (admins can run for any).
	const [content] = await db
		.select({ id: mediaLibrary.id, creatorId: mediaLibrary.creatorId, title: mediaLibrary.title, duration: mediaLibrary.duration })
		.from(mediaLibrary)
		.where(eq(mediaLibrary.id, contentId))
		.limit(1);
	if (!content) return json({ error: 'Content not found' }, { status: 404 });
	if (session.user.role !== Role.ADMIN && content.creatorId !== session.user.id) {
		return json({ error: 'Forbidden' }, { status: 403 });
	}

	// Prefer auto-generated tracks (orchestrator Whisper output); fall back
	// to any track.
	const autoTracks = await db
		.select({ fileUrl: contentSubtitleTracks.fileUrl })
		.from(contentSubtitleTracks)
		.where(and(eq(contentSubtitleTracks.contentId, contentId), eq(contentSubtitleTracks.autoGenerated, true)))
		.limit(1);
	let track = autoTracks[0];
	if (!track) {
		const anyTracks = await db
			.select({ fileUrl: contentSubtitleTracks.fileUrl })
			.from(contentSubtitleTracks)
			.where(eq(contentSubtitleTracks.contentId, contentId))
			.limit(1);
		track = anyTracks[0];
	}

	if (!track) {
		return json({ error: 'No transcript available. Run the content scan first or upload subtitles.' }, { status: 409 });
	}

	let vtt: string;
	try {
		const res = await fetch(track.fileUrl);
		if (!res.ok) throw new Error(`status ${res.status}`);
		vtt = await res.text();
	} catch (err) {
		return json({ error: `Couldn't fetch transcript: ${err instanceof Error ? err.message : 'unknown error'}` }, { status: 502 });
	}

	const cues = parseVtt(vtt);
	if (cues.length === 0) {
		return json({ error: 'Transcript was empty or malformed.' }, { status: 422 });
	}

	const transcriptDigest = digest(cues, 6000);

	const result = await runAi({
		userId: session.user.id,
		surface: 'creator:suggest-chapters',
		modelType: 'agent',
		temperature: 0.3,
		maxTokens: 700,
		messages: [
			{
				role: 'system',
				content: 'You break long-form video transcripts into clear chapter markers for viewers. Faith-based / Christian platform. Be precise on timestamps and concise on titles.'
			},
			{
				role: 'user',
				content: `Suggest 5-12 chapter markers for the video titled "${content.title}".

Transcript (sampled across the video, with [Ns] timestamps):
"""
${transcriptDigest}
"""

Return ONLY this JSON:
{ "suggestions": [{ "start": <integer seconds>, "title": "<3-7 word chapter title>" }, ...] }

Rules:
- start MUST be one of the [Ns] timestamps from the transcript above (or very close, in whole seconds)
- First chapter starts at 0
- Timestamps strictly increasing
- Titles 3-7 words, sentence case, NO trailing punctuation
- Pick natural topic transitions, not arbitrary time slices
- Maximum 12 chapters`
			}
		]
	});

	if (!result.ok) {
		const status = result.error === 'budget_exceeded' ? 429 : 503;
		return json({ error: result.message }, { status });
	}

	const parsed = tryParseJson<{ suggestions?: unknown }>(result.content);
	const raw = Array.isArray(parsed?.suggestions) ? parsed.suggestions : [];

	// Sanitize: numeric monotonic starts, trimmed titles, max 12.
	const seen = new Set<number>();
	const cleaned: Array<{ start: number; title: string }> = [];
	let lastStart = -1;
	for (const item of raw) {
		if (!item || typeof item !== 'object') continue;
		const obj = item as { start?: unknown; title?: unknown };
		const start = Math.max(0, Math.round(Number(obj.start ?? -1)));
		const title = String(obj.title ?? '').trim().slice(0, 80);
		if (!title || Number.isNaN(start) || start <= lastStart || seen.has(start)) continue;
		cleaned.push({ start, title });
		seen.add(start);
		lastStart = start;
		if (cleaned.length >= 12) break;
	}

	if (cleaned.length === 0) {
		return json({ error: 'AI did not return valid chapter suggestions.' }, { status: 502 });
	}
	// Ensure the first chapter is at 0; if not, prepend an "Intro" chapter
	// so the player has a starting marker.
	if (cleaned[0].start !== 0) {
		cleaned.unshift({ start: 0, title: 'Intro' });
	}

	return json({ suggestions: cleaned });
};
