
// this file is generated — do not edit it


declare module "svelte/elements" {
	export interface HTMLAttributes<T> {
		'data-sveltekit-keepfocus'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-noscroll'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-preload-code'?:
			| true
			| ''
			| 'eager'
			| 'viewport'
			| 'hover'
			| 'tap'
			| 'off'
			| undefined
			| null;
		'data-sveltekit-preload-data'?: true | '' | 'hover' | 'tap' | 'off' | undefined | null;
		'data-sveltekit-reload'?: true | '' | 'off' | undefined | null;
		'data-sveltekit-replacestate'?: true | '' | 'off' | undefined | null;
	}
}

export {};


declare module "$app/types" {
	type MatcherParam<M> = M extends (param : string) => param is (infer U extends string) ? U : string;

	export interface AppTypes {
		RouteId(): "/(web3)" | "/(protected)" | "/(creator)" | "/(auth)" | "/(app)" | "/(admin)" | "/" | "/(app)/about" | "/(protected)/achievements" | "/(admin)/admin" | "/(admin)/admin/analytics" | "/(admin)/admin/communications" | "/(admin)/admin/content" | "/(admin)/admin/creator-applications" | "/(admin)/admin/creators" | "/(admin)/admin/dashboard" | "/(admin)/admin/events" | "/(admin)/admin/governance" | "/(admin)/admin/governance/create" | "/(admin)/admin/governance/emergency" | "/(admin)/admin/governance/execution" | "/(admin)/admin/governance/proposals" | "/(admin)/admin/governance/reports" | "/(admin)/admin/governance/roles" | "/(admin)/admin/governance/treasury" | "/(admin)/admin/policies" | "/(admin)/admin/review" | "/(admin)/admin/review/[id]" | "/(admin)/admin/settings" | "/(admin)/admin/submissions" | "/(admin)/admin/tokenomics" | "/(admin)/admin/workflow" | "/api" | "/api/achievements" | "/api/admin" | "/api/admin/admins" | "/api/admin/ai" | "/api/admin/ai/config" | "/api/admin/ai/models" | "/api/admin/ai/test" | "/api/admin/analytics" | "/api/admin/communications" | "/api/admin/communications/templates" | "/api/admin/content" | "/api/admin/content/bulk" | "/api/admin/content/[id]" | "/api/admin/content/[id]/assign" | "/api/admin/content/[id]/ppv" | "/api/admin/content/[id]/publish" | "/api/admin/content/[id]/review" | "/api/admin/creator-applications" | "/api/admin/creator-applications/[id]" | "/api/admin/creator-applications/[id]/review" | "/api/admin/creators" | "/api/admin/events" | "/api/admin/events/[id]" | "/api/admin/forum" | "/api/admin/forum/threads" | "/api/admin/forum/threads/[id]" | "/api/admin/governance" | "/api/admin/governance/approve" | "/api/admin/governance/audit" | "/api/admin/governance/emergency" | "/api/admin/governance/emergency/pause" | "/api/admin/governance/execute" | "/api/admin/governance/proposals" | "/api/admin/governance/queue" | "/api/admin/governance/reports" | "/api/admin/governance/roles" | "/api/admin/governance/status" | "/api/admin/governance/timelock-queue" | "/api/admin/governance/treasury" | "/api/admin/policies" | "/api/admin/refunds" | "/api/admin/reviews" | "/api/admin/settings" | "/api/admin/settings/test-email" | "/api/admin/sponsorships" | "/api/admin/sponsorships/[id]" | "/api/admin/sponsorships/[id]/review" | "/api/admin/stats" | "/api/admin/success-stories" | "/api/admin/success-stories/[id]" | "/api/admin/success-stories/[id]/review" | "/api/admin/support-tickets" | "/api/admin/support-tickets/[id]" | "/api/admin/support-tickets/[id]/review" | "/api/admin/tokenomics" | "/api/admin/tokenomics/distribution" | "/api/admin/users" | "/api/admin/users/stats" | "/api/admin/workflow" | "/api/admin/workflow/stats" | "/api/ai" | "/api/ai/companion" | "/api/ai/creator-insights" | "/api/ai/moderate" | "/api/ai/nft" | "/api/ai/search" | "/api/ai/tag" | "/api/ai/token-score" | "/api/auth" | "/api/auth/[...all]" | "/api/contact" | "/api/content" | "/api/content/kids" | "/api/creators" | "/api/creators/[id]" | "/api/creators/[id]/follow" | "/api/creator" | "/api/creator/analytics" | "/api/creator/application" | "/api/creator/content" | "/api/creator/content/[id]" | "/api/creator/content/[id]/duplicate" | "/api/creator/earnings" | "/api/creator/newsletter" | "/api/creator/newsletter/subscribe" | "/api/creator/payment-preferences" | "/api/creator/profile" | "/api/creator/stats" | "/api/cron" | "/api/cron/creator-payouts" | "/api/cron/event-status-sweep" | "/api/cron/meilisearch-reindex" | "/api/cron/newsletter-weekly-digest" | "/api/cron/renew-subscriptions" | "/api/cron/settlement-reconcile" | "/api/cron/staking-indexer" | "/api/downloads" | "/api/downloads/manifest" | "/api/downloads/manifest/[id]" | "/api/encoder" | "/api/encoder/jobs" | "/api/encoder/jobs/[jobId]" | "/api/encoder/jobs/[jobId]/commit" | "/api/encoder/jobs/[jobId]/playback" | "/api/encoder/pending" | "/api/encoder/presigned" | "/api/encoder/process" | "/api/encoder/ready" | "/api/events" | "/api/events/feed.ics" | "/api/events/[id]" | "/api/events/[id]/register" | "/api/files" | "/api/forum" | "/api/forum/replies" | "/api/forum/replies/[id]" | "/api/forum/replies/[id]/like" | "/api/forum/threads" | "/api/forum/threads/[id]" | "/api/forum/threads/[id]/like" | "/api/forum/threads/[id]/replies" | "/api/health" | "/api/kids" | "/api/kids/quiz" | "/api/kids/quiz/generate" | "/api/kids/quiz/submit" | "/api/milestones" | "/api/notifications" | "/api/notifications/preferences" | "/api/notifications/[id]" | "/api/notifications/[id]/read" | "/api/parental" | "/api/parental/report" | "/api/payment" | "/api/payment/initialize" | "/api/payment/verify" | "/api/payment/webhook" | "/api/playlists" | "/api/playlists/[id]" | "/api/playlists/[id]/items" | "/api/ppv" | "/api/ppv/check-access" | "/api/ppv/check-access/[contentId]" | "/api/ppv/purchase" | "/api/ppv/refund" | "/api/profiles" | "/api/profiles/current" | "/api/profiles/[id]" | "/api/profiles/[id]/pin" | "/api/push" | "/api/push/subscribe" | "/api/recommendations" | "/api/reviews" | "/api/reviews/[id]" | "/api/reviews/[id]/helpful" | "/api/search" | "/api/shares" | "/api/subscriptions" | "/api/subscriptions/add-family" | "/api/subscriptions/cancel" | "/api/subscriptions/change-plan" | "/api/subscriptions/send-otp" | "/api/subscriptions/start-trial" | "/api/subscriptions/status" | "/api/success-stories" | "/api/support" | "/api/support/tickets" | "/api/users" | "/api/users/me" | "/api/users/me/stc-balance" | "/api/users/me/stc-claim" | "/api/users/[id]" | "/api/user" | "/api/user/profile" | "/api/watch" | "/api/watch/active" | "/api/watch/history" | "/api/watch/progress" | "/api/watch/[videoId]" | "/(app)/apply" | "/(app)/apply/creator" | "/(app)/archive" | "/(auth)/auth" | "/(auth)/auth/forget-password" | "/(auth)/auth/forget-password/success" | "/(auth)/auth/login" | "/(auth)/auth/register" | "/(auth)/auth/reset-password" | "/(app)/browse" | "/(app)/careers" | "/(app)/checkout" | "/(app)/contact" | "/(app)/creators" | "/(app)/creators/[id]" | "/(creator)/creator" | "/(creator)/creator/agreement" | "/(creator)/creator/analytics-help" | "/(creator)/creator/analytics" | "/(creator)/creator/best-practices" | "/(creator)/creator/content" | "/(creator)/creator/copyright" | "/(creator)/creator/earnings" | "/(creator)/creator/events" | "/(creator)/creator/forum" | "/(creator)/creator/forum/new" | "/(creator)/creator/forum/[id]" | "/(creator)/creator/guidelines" | "/(creator)/creator/newsletter" | "/(creator)/creator/profile" | "/(creator)/creator/success-stories" | "/(creator)/creator/support" | "/(creator)/creator/tech-support" | "/(creator)/creator/test" | "/(creator)/creator/upload" | "/(protected)/dashboard" | "/(app)/device-support" | "/(app)/documentaries" | "/(protected)/documentation" | "/(app)/exchange" | "/(app)/faq" | "/(app)/features" | "/(app)/guidelines" | "/(app)/help" | "/kids" | "/kids/kiddies" | "/kids/kiddies/bible-quiz" | "/kids/kiddies/documentaries" | "/kids/kiddies/movies" | "/kids/kiddies/profile" | "/kids/kiddies/shows" | "/kids/teens" | "/(app)/liquidity" | "/(protected)/milestones" | "/(app)/movies" | "/(app)/my-studios" | "/(app)/offline" | "/(protected)/parental-controls" | "/(app)/plans" | "/(app)/press" | "/(app)/privacy" | "/(protected)/profiles" | "/(protected)/profile" | "/(app)/search" | "/(protected)/settings" | "/(app)/shows" | "/sitemap.xml" | "/(app)/sponsorships" | "/(app)/staking" | "/(web3)/subscription" | "/(app)/terms" | "/(web3)/tokens" | "/(app)/token" | "/(protected)/users" | "/(protected)/users/components" | "/(web3)/wallet" | "/(protected)/watchlist" | "/watch" | "/watch/[id]" | "/(app)/webinars";
		RouteParams(): {
			"/(admin)/admin/review/[id]": { id: string };
			"/api/admin/content/[id]": { id: string };
			"/api/admin/content/[id]/assign": { id: string };
			"/api/admin/content/[id]/ppv": { id: string };
			"/api/admin/content/[id]/publish": { id: string };
			"/api/admin/content/[id]/review": { id: string };
			"/api/admin/creator-applications/[id]": { id: string };
			"/api/admin/creator-applications/[id]/review": { id: string };
			"/api/admin/events/[id]": { id: string };
			"/api/admin/forum/threads/[id]": { id: string };
			"/api/admin/sponsorships/[id]": { id: string };
			"/api/admin/sponsorships/[id]/review": { id: string };
			"/api/admin/success-stories/[id]": { id: string };
			"/api/admin/success-stories/[id]/review": { id: string };
			"/api/admin/support-tickets/[id]": { id: string };
			"/api/admin/support-tickets/[id]/review": { id: string };
			"/api/auth/[...all]": { all: string };
			"/api/creators/[id]": { id: string };
			"/api/creators/[id]/follow": { id: string };
			"/api/creator/content/[id]": { id: string };
			"/api/creator/content/[id]/duplicate": { id: string };
			"/api/downloads/manifest/[id]": { id: string };
			"/api/encoder/jobs/[jobId]": { jobId: string };
			"/api/encoder/jobs/[jobId]/commit": { jobId: string };
			"/api/encoder/jobs/[jobId]/playback": { jobId: string };
			"/api/events/[id]": { id: string };
			"/api/events/[id]/register": { id: string };
			"/api/forum/replies/[id]": { id: string };
			"/api/forum/replies/[id]/like": { id: string };
			"/api/forum/threads/[id]": { id: string };
			"/api/forum/threads/[id]/like": { id: string };
			"/api/forum/threads/[id]/replies": { id: string };
			"/api/notifications/[id]": { id: string };
			"/api/notifications/[id]/read": { id: string };
			"/api/playlists/[id]": { id: string };
			"/api/playlists/[id]/items": { id: string };
			"/api/ppv/check-access/[contentId]": { contentId: string };
			"/api/profiles/[id]": { id: string };
			"/api/profiles/[id]/pin": { id: string };
			"/api/reviews/[id]": { id: string };
			"/api/reviews/[id]/helpful": { id: string };
			"/api/users/[id]": { id: string };
			"/api/watch/[videoId]": { videoId: string };
			"/(app)/creators/[id]": { id: string };
			"/(creator)/creator/forum/[id]": { id: string };
			"/watch/[id]": { id: string }
		};
		LayoutParams(): {
			"/(web3)": Record<string, never>;
			"/(protected)": Record<string, never>;
			"/(creator)": { id?: string | undefined };
			"/(auth)": Record<string, never>;
			"/(app)": { id?: string | undefined };
			"/(admin)": { id?: string | undefined };
			"/": { id?: string | undefined; all?: string | undefined; jobId?: string | undefined; contentId?: string | undefined; videoId?: string | undefined };
			"/(app)/about": Record<string, never>;
			"/(protected)/achievements": Record<string, never>;
			"/(admin)/admin": { id?: string | undefined };
			"/(admin)/admin/analytics": Record<string, never>;
			"/(admin)/admin/communications": Record<string, never>;
			"/(admin)/admin/content": Record<string, never>;
			"/(admin)/admin/creator-applications": Record<string, never>;
			"/(admin)/admin/creators": Record<string, never>;
			"/(admin)/admin/dashboard": Record<string, never>;
			"/(admin)/admin/events": Record<string, never>;
			"/(admin)/admin/governance": Record<string, never>;
			"/(admin)/admin/governance/create": Record<string, never>;
			"/(admin)/admin/governance/emergency": Record<string, never>;
			"/(admin)/admin/governance/execution": Record<string, never>;
			"/(admin)/admin/governance/proposals": Record<string, never>;
			"/(admin)/admin/governance/reports": Record<string, never>;
			"/(admin)/admin/governance/roles": Record<string, never>;
			"/(admin)/admin/governance/treasury": Record<string, never>;
			"/(admin)/admin/policies": Record<string, never>;
			"/(admin)/admin/review": { id?: string | undefined };
			"/(admin)/admin/review/[id]": { id: string };
			"/(admin)/admin/settings": Record<string, never>;
			"/(admin)/admin/submissions": Record<string, never>;
			"/(admin)/admin/tokenomics": Record<string, never>;
			"/(admin)/admin/workflow": Record<string, never>;
			"/api": { id?: string | undefined; all?: string | undefined; jobId?: string | undefined; contentId?: string | undefined; videoId?: string | undefined };
			"/api/achievements": Record<string, never>;
			"/api/admin": { id?: string | undefined };
			"/api/admin/admins": Record<string, never>;
			"/api/admin/ai": Record<string, never>;
			"/api/admin/ai/config": Record<string, never>;
			"/api/admin/ai/models": Record<string, never>;
			"/api/admin/ai/test": Record<string, never>;
			"/api/admin/analytics": Record<string, never>;
			"/api/admin/communications": Record<string, never>;
			"/api/admin/communications/templates": Record<string, never>;
			"/api/admin/content": { id?: string | undefined };
			"/api/admin/content/bulk": Record<string, never>;
			"/api/admin/content/[id]": { id: string };
			"/api/admin/content/[id]/assign": { id: string };
			"/api/admin/content/[id]/ppv": { id: string };
			"/api/admin/content/[id]/publish": { id: string };
			"/api/admin/content/[id]/review": { id: string };
			"/api/admin/creator-applications": { id?: string | undefined };
			"/api/admin/creator-applications/[id]": { id: string };
			"/api/admin/creator-applications/[id]/review": { id: string };
			"/api/admin/creators": Record<string, never>;
			"/api/admin/events": { id?: string | undefined };
			"/api/admin/events/[id]": { id: string };
			"/api/admin/forum": { id?: string | undefined };
			"/api/admin/forum/threads": { id?: string | undefined };
			"/api/admin/forum/threads/[id]": { id: string };
			"/api/admin/governance": Record<string, never>;
			"/api/admin/governance/approve": Record<string, never>;
			"/api/admin/governance/audit": Record<string, never>;
			"/api/admin/governance/emergency": Record<string, never>;
			"/api/admin/governance/emergency/pause": Record<string, never>;
			"/api/admin/governance/execute": Record<string, never>;
			"/api/admin/governance/proposals": Record<string, never>;
			"/api/admin/governance/queue": Record<string, never>;
			"/api/admin/governance/reports": Record<string, never>;
			"/api/admin/governance/roles": Record<string, never>;
			"/api/admin/governance/status": Record<string, never>;
			"/api/admin/governance/timelock-queue": Record<string, never>;
			"/api/admin/governance/treasury": Record<string, never>;
			"/api/admin/policies": Record<string, never>;
			"/api/admin/refunds": Record<string, never>;
			"/api/admin/reviews": Record<string, never>;
			"/api/admin/settings": Record<string, never>;
			"/api/admin/settings/test-email": Record<string, never>;
			"/api/admin/sponsorships": { id?: string | undefined };
			"/api/admin/sponsorships/[id]": { id: string };
			"/api/admin/sponsorships/[id]/review": { id: string };
			"/api/admin/stats": Record<string, never>;
			"/api/admin/success-stories": { id?: string | undefined };
			"/api/admin/success-stories/[id]": { id: string };
			"/api/admin/success-stories/[id]/review": { id: string };
			"/api/admin/support-tickets": { id?: string | undefined };
			"/api/admin/support-tickets/[id]": { id: string };
			"/api/admin/support-tickets/[id]/review": { id: string };
			"/api/admin/tokenomics": Record<string, never>;
			"/api/admin/tokenomics/distribution": Record<string, never>;
			"/api/admin/users": Record<string, never>;
			"/api/admin/users/stats": Record<string, never>;
			"/api/admin/workflow": Record<string, never>;
			"/api/admin/workflow/stats": Record<string, never>;
			"/api/ai": Record<string, never>;
			"/api/ai/companion": Record<string, never>;
			"/api/ai/creator-insights": Record<string, never>;
			"/api/ai/moderate": Record<string, never>;
			"/api/ai/nft": Record<string, never>;
			"/api/ai/search": Record<string, never>;
			"/api/ai/tag": Record<string, never>;
			"/api/ai/token-score": Record<string, never>;
			"/api/auth": { all?: string | undefined };
			"/api/auth/[...all]": { all: string };
			"/api/contact": Record<string, never>;
			"/api/content": Record<string, never>;
			"/api/content/kids": Record<string, never>;
			"/api/creators": { id?: string | undefined };
			"/api/creators/[id]": { id: string };
			"/api/creators/[id]/follow": { id: string };
			"/api/creator": { id?: string | undefined };
			"/api/creator/analytics": Record<string, never>;
			"/api/creator/application": Record<string, never>;
			"/api/creator/content": { id?: string | undefined };
			"/api/creator/content/[id]": { id: string };
			"/api/creator/content/[id]/duplicate": { id: string };
			"/api/creator/earnings": Record<string, never>;
			"/api/creator/newsletter": Record<string, never>;
			"/api/creator/newsletter/subscribe": Record<string, never>;
			"/api/creator/payment-preferences": Record<string, never>;
			"/api/creator/profile": Record<string, never>;
			"/api/creator/stats": Record<string, never>;
			"/api/cron": Record<string, never>;
			"/api/cron/creator-payouts": Record<string, never>;
			"/api/cron/event-status-sweep": Record<string, never>;
			"/api/cron/meilisearch-reindex": Record<string, never>;
			"/api/cron/newsletter-weekly-digest": Record<string, never>;
			"/api/cron/renew-subscriptions": Record<string, never>;
			"/api/cron/settlement-reconcile": Record<string, never>;
			"/api/cron/staking-indexer": Record<string, never>;
			"/api/downloads": { id?: string | undefined };
			"/api/downloads/manifest": { id?: string | undefined };
			"/api/downloads/manifest/[id]": { id: string };
			"/api/encoder": { jobId?: string | undefined };
			"/api/encoder/jobs": { jobId?: string | undefined };
			"/api/encoder/jobs/[jobId]": { jobId: string };
			"/api/encoder/jobs/[jobId]/commit": { jobId: string };
			"/api/encoder/jobs/[jobId]/playback": { jobId: string };
			"/api/encoder/pending": Record<string, never>;
			"/api/encoder/presigned": Record<string, never>;
			"/api/encoder/process": Record<string, never>;
			"/api/encoder/ready": Record<string, never>;
			"/api/events": { id?: string | undefined };
			"/api/events/feed.ics": Record<string, never>;
			"/api/events/[id]": { id: string };
			"/api/events/[id]/register": { id: string };
			"/api/files": Record<string, never>;
			"/api/forum": { id?: string | undefined };
			"/api/forum/replies": { id?: string | undefined };
			"/api/forum/replies/[id]": { id: string };
			"/api/forum/replies/[id]/like": { id: string };
			"/api/forum/threads": { id?: string | undefined };
			"/api/forum/threads/[id]": { id: string };
			"/api/forum/threads/[id]/like": { id: string };
			"/api/forum/threads/[id]/replies": { id: string };
			"/api/health": Record<string, never>;
			"/api/kids": Record<string, never>;
			"/api/kids/quiz": Record<string, never>;
			"/api/kids/quiz/generate": Record<string, never>;
			"/api/kids/quiz/submit": Record<string, never>;
			"/api/milestones": Record<string, never>;
			"/api/notifications": { id?: string | undefined };
			"/api/notifications/preferences": Record<string, never>;
			"/api/notifications/[id]": { id: string };
			"/api/notifications/[id]/read": { id: string };
			"/api/parental": Record<string, never>;
			"/api/parental/report": Record<string, never>;
			"/api/payment": Record<string, never>;
			"/api/payment/initialize": Record<string, never>;
			"/api/payment/verify": Record<string, never>;
			"/api/payment/webhook": Record<string, never>;
			"/api/playlists": { id?: string | undefined };
			"/api/playlists/[id]": { id: string };
			"/api/playlists/[id]/items": { id: string };
			"/api/ppv": { contentId?: string | undefined };
			"/api/ppv/check-access": { contentId?: string | undefined };
			"/api/ppv/check-access/[contentId]": { contentId: string };
			"/api/ppv/purchase": Record<string, never>;
			"/api/ppv/refund": Record<string, never>;
			"/api/profiles": { id?: string | undefined };
			"/api/profiles/current": Record<string, never>;
			"/api/profiles/[id]": { id: string };
			"/api/profiles/[id]/pin": { id: string };
			"/api/push": Record<string, never>;
			"/api/push/subscribe": Record<string, never>;
			"/api/recommendations": Record<string, never>;
			"/api/reviews": { id?: string | undefined };
			"/api/reviews/[id]": { id: string };
			"/api/reviews/[id]/helpful": { id: string };
			"/api/search": Record<string, never>;
			"/api/shares": Record<string, never>;
			"/api/subscriptions": Record<string, never>;
			"/api/subscriptions/add-family": Record<string, never>;
			"/api/subscriptions/cancel": Record<string, never>;
			"/api/subscriptions/change-plan": Record<string, never>;
			"/api/subscriptions/send-otp": Record<string, never>;
			"/api/subscriptions/start-trial": Record<string, never>;
			"/api/subscriptions/status": Record<string, never>;
			"/api/success-stories": Record<string, never>;
			"/api/support": Record<string, never>;
			"/api/support/tickets": Record<string, never>;
			"/api/users": { id?: string | undefined };
			"/api/users/me": Record<string, never>;
			"/api/users/me/stc-balance": Record<string, never>;
			"/api/users/me/stc-claim": Record<string, never>;
			"/api/users/[id]": { id: string };
			"/api/user": Record<string, never>;
			"/api/user/profile": Record<string, never>;
			"/api/watch": { videoId?: string | undefined };
			"/api/watch/active": Record<string, never>;
			"/api/watch/history": Record<string, never>;
			"/api/watch/progress": Record<string, never>;
			"/api/watch/[videoId]": { videoId: string };
			"/(app)/apply": Record<string, never>;
			"/(app)/apply/creator": Record<string, never>;
			"/(app)/archive": Record<string, never>;
			"/(auth)/auth": Record<string, never>;
			"/(auth)/auth/forget-password": Record<string, never>;
			"/(auth)/auth/forget-password/success": Record<string, never>;
			"/(auth)/auth/login": Record<string, never>;
			"/(auth)/auth/register": Record<string, never>;
			"/(auth)/auth/reset-password": Record<string, never>;
			"/(app)/browse": Record<string, never>;
			"/(app)/careers": Record<string, never>;
			"/(app)/checkout": Record<string, never>;
			"/(app)/contact": Record<string, never>;
			"/(app)/creators": { id?: string | undefined };
			"/(app)/creators/[id]": { id: string };
			"/(creator)/creator": { id?: string | undefined };
			"/(creator)/creator/agreement": Record<string, never>;
			"/(creator)/creator/analytics-help": Record<string, never>;
			"/(creator)/creator/analytics": Record<string, never>;
			"/(creator)/creator/best-practices": Record<string, never>;
			"/(creator)/creator/content": Record<string, never>;
			"/(creator)/creator/copyright": Record<string, never>;
			"/(creator)/creator/earnings": Record<string, never>;
			"/(creator)/creator/events": Record<string, never>;
			"/(creator)/creator/forum": { id?: string | undefined };
			"/(creator)/creator/forum/new": Record<string, never>;
			"/(creator)/creator/forum/[id]": { id: string };
			"/(creator)/creator/guidelines": Record<string, never>;
			"/(creator)/creator/newsletter": Record<string, never>;
			"/(creator)/creator/profile": Record<string, never>;
			"/(creator)/creator/success-stories": Record<string, never>;
			"/(creator)/creator/support": Record<string, never>;
			"/(creator)/creator/tech-support": Record<string, never>;
			"/(creator)/creator/test": Record<string, never>;
			"/(creator)/creator/upload": Record<string, never>;
			"/(protected)/dashboard": Record<string, never>;
			"/(app)/device-support": Record<string, never>;
			"/(app)/documentaries": Record<string, never>;
			"/(protected)/documentation": Record<string, never>;
			"/(app)/exchange": Record<string, never>;
			"/(app)/faq": Record<string, never>;
			"/(app)/features": Record<string, never>;
			"/(app)/guidelines": Record<string, never>;
			"/(app)/help": Record<string, never>;
			"/kids": Record<string, never>;
			"/kids/kiddies": Record<string, never>;
			"/kids/kiddies/bible-quiz": Record<string, never>;
			"/kids/kiddies/documentaries": Record<string, never>;
			"/kids/kiddies/movies": Record<string, never>;
			"/kids/kiddies/profile": Record<string, never>;
			"/kids/kiddies/shows": Record<string, never>;
			"/kids/teens": Record<string, never>;
			"/(app)/liquidity": Record<string, never>;
			"/(protected)/milestones": Record<string, never>;
			"/(app)/movies": Record<string, never>;
			"/(app)/my-studios": Record<string, never>;
			"/(app)/offline": Record<string, never>;
			"/(protected)/parental-controls": Record<string, never>;
			"/(app)/plans": Record<string, never>;
			"/(app)/press": Record<string, never>;
			"/(app)/privacy": Record<string, never>;
			"/(protected)/profiles": Record<string, never>;
			"/(protected)/profile": Record<string, never>;
			"/(app)/search": Record<string, never>;
			"/(protected)/settings": Record<string, never>;
			"/(app)/shows": Record<string, never>;
			"/sitemap.xml": Record<string, never>;
			"/(app)/sponsorships": Record<string, never>;
			"/(app)/staking": Record<string, never>;
			"/(web3)/subscription": Record<string, never>;
			"/(app)/terms": Record<string, never>;
			"/(web3)/tokens": Record<string, never>;
			"/(app)/token": Record<string, never>;
			"/(protected)/users": Record<string, never>;
			"/(protected)/users/components": Record<string, never>;
			"/(web3)/wallet": Record<string, never>;
			"/(protected)/watchlist": Record<string, never>;
			"/watch": { id?: string | undefined };
			"/watch/[id]": { id: string };
			"/(app)/webinars": Record<string, never>
		};
		Pathname(): "/" | "/about" | "/achievements" | "/admin" | "/admin/analytics" | "/admin/communications" | "/admin/content" | "/admin/creator-applications" | "/admin/creators" | "/admin/dashboard" | "/admin/events" | "/admin/governance" | "/admin/governance/create" | "/admin/governance/emergency" | "/admin/governance/execution" | "/admin/governance/proposals" | "/admin/governance/reports" | "/admin/governance/roles" | "/admin/governance/treasury" | "/admin/policies" | "/admin/review" | `/admin/review/${string}` & {} | "/admin/settings" | "/admin/submissions" | "/admin/tokenomics" | "/admin/workflow" | "/api/achievements" | "/api/admin/admins" | "/api/admin/ai/config" | "/api/admin/ai/models" | "/api/admin/ai/test" | "/api/admin/analytics" | "/api/admin/communications" | "/api/admin/communications/templates" | "/api/admin/content" | "/api/admin/content/bulk" | `/api/admin/content/${string}` & {} | `/api/admin/content/${string}/assign` & {} | `/api/admin/content/${string}/ppv` & {} | `/api/admin/content/${string}/publish` & {} | `/api/admin/content/${string}/review` & {} | "/api/admin/creator-applications" | `/api/admin/creator-applications/${string}/review` & {} | "/api/admin/creators" | "/api/admin/events" | `/api/admin/events/${string}` & {} | `/api/admin/forum/threads/${string}` & {} | "/api/admin/governance/approve" | "/api/admin/governance/audit" | "/api/admin/governance/emergency/pause" | "/api/admin/governance/execute" | "/api/admin/governance/proposals" | "/api/admin/governance/queue" | "/api/admin/governance/reports" | "/api/admin/governance/roles" | "/api/admin/governance/status" | "/api/admin/governance/timelock-queue" | "/api/admin/governance/treasury" | "/api/admin/policies" | "/api/admin/refunds" | "/api/admin/reviews" | "/api/admin/settings" | "/api/admin/settings/test-email" | "/api/admin/sponsorships" | `/api/admin/sponsorships/${string}/review` & {} | "/api/admin/stats" | "/api/admin/success-stories" | `/api/admin/success-stories/${string}/review` & {} | "/api/admin/support-tickets" | `/api/admin/support-tickets/${string}/review` & {} | "/api/admin/tokenomics" | "/api/admin/tokenomics/distribution" | "/api/admin/users/stats" | "/api/admin/workflow" | "/api/admin/workflow/stats" | "/api/ai/companion" | "/api/ai/creator-insights" | "/api/ai/moderate" | "/api/ai/nft" | "/api/ai/search" | "/api/ai/tag" | "/api/ai/token-score" | `/api/auth/${string}` & {} | "/api/contact" | "/api/content/kids" | `/api/creators/${string}/follow` & {} | "/api/creator/analytics" | "/api/creator/application" | "/api/creator/content" | `/api/creator/content/${string}/duplicate` & {} | "/api/creator/earnings" | "/api/creator/newsletter/subscribe" | "/api/creator/payment-preferences" | "/api/creator/profile" | "/api/creator/stats" | "/api/cron/creator-payouts" | "/api/cron/event-status-sweep" | "/api/cron/meilisearch-reindex" | "/api/cron/newsletter-weekly-digest" | "/api/cron/renew-subscriptions" | "/api/cron/settlement-reconcile" | "/api/cron/settlement-reconcile/" | "/api/cron/staking-indexer" | `/api/downloads/manifest/${string}` & {} | "/api/encoder/jobs" | `/api/encoder/jobs/${string}` & {} | `/api/encoder/jobs/${string}/commit` & {} | `/api/encoder/jobs/${string}/playback` & {} | "/api/encoder/pending" | "/api/encoder/presigned" | "/api/encoder/process" | "/api/encoder/ready" | "/api/events" | "/api/events/feed.ics" | `/api/events/${string}` & {} | `/api/events/${string}/register` & {} | "/api/files" | `/api/forum/replies/${string}` & {} | `/api/forum/replies/${string}/like` & {} | "/api/forum/threads" | `/api/forum/threads/${string}` & {} | `/api/forum/threads/${string}/like` & {} | `/api/forum/threads/${string}/replies` & {} | "/api/health" | "/api/kids/quiz/generate" | "/api/kids/quiz/submit" | "/api/milestones" | "/api/notifications" | "/api/notifications/preferences" | `/api/notifications/${string}` & {} | `/api/notifications/${string}/read` & {} | "/api/parental/report" | "/api/payment/initialize" | "/api/payment/verify" | "/api/payment/webhook" | "/api/playlists" | `/api/playlists/${string}/items` & {} | `/api/ppv/check-access/${string}` & {} | "/api/ppv/purchase" | "/api/ppv/refund" | "/api/profiles" | "/api/profiles/current" | `/api/profiles/${string}` & {} | `/api/profiles/${string}/pin` & {} | "/api/push/subscribe" | "/api/recommendations" | "/api/reviews" | `/api/reviews/${string}/helpful` & {} | "/api/search" | "/api/shares" | "/api/subscriptions/add-family" | "/api/subscriptions/cancel" | "/api/subscriptions/change-plan" | "/api/subscriptions/send-otp" | "/api/subscriptions/start-trial" | "/api/subscriptions/status" | "/api/success-stories" | "/api/support/tickets" | "/api/users" | "/api/users/me/stc-balance" | "/api/users/me/stc-claim" | `/api/users/${string}` & {} | "/api/user/profile" | "/api/watch/active" | "/api/watch/history" | "/api/watch/progress" | `/api/watch/${string}` & {} | "/apply/creator" | "/archive" | "/auth/forget-password" | "/auth/forget-password/success" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/browse" | "/careers" | "/checkout" | "/contact" | `/creators/${string}` & {} | "/creator" | "/creator/agreement" | "/creator/analytics-help" | "/creator/analytics" | "/creator/best-practices" | "/creator/content" | "/creator/copyright" | "/creator/earnings" | "/creator/events" | "/creator/forum" | "/creator/forum/new" | `/creator/forum/${string}` & {} | "/creator/guidelines" | "/creator/newsletter" | "/creator/profile" | "/creator/success-stories" | "/creator/support" | "/creator/tech-support" | "/creator/test" | "/creator/upload" | "/dashboard" | "/device-support" | "/documentaries" | "/documentation" | "/exchange" | "/faq" | "/features" | "/guidelines" | "/help" | "/kids/kiddies" | "/kids/kiddies/bible-quiz" | "/kids/kiddies/documentaries" | "/kids/kiddies/movies" | "/kids/kiddies/profile" | "/kids/kiddies/shows" | "/kids/teens" | "/liquidity" | "/milestones" | "/movies" | "/my-studios" | "/offline" | "/parental-controls" | "/plans" | "/press" | "/privacy" | "/profiles" | "/profile" | "/search" | "/settings" | "/shows" | "/sitemap.xml" | "/sponsorships" | "/staking" | "/subscription" | "/terms" | "/tokens" | "/token" | "/users" | "/wallet" | "/watchlist" | `/watch/${string}` & {} | "/webinars";
		ResolvedPathname(): `${"" | `/${string}`}${ReturnType<AppTypes['Pathname']>}`;
		Asset(): "/asl-logo.png" | "/favicon-96x96.png" | "/favicon.ico" | "/favicon.svg" | "/logo&name-sepharstudios.png" | "/logo-alone-sepharstudios-bgless.png" | "/logo-alone-sepharstudios.png" | "/logo_name-sepharstudios.png" | "/manifest.json" | "/name-alone-sepharstudios.png" | "/pwa-192x192.png" | "/pwa-512x512.png" | "/pwa-maskable-192x192.png" | "/pwa-maskable-512x512.png" | "/robots.txt" | "/screenshot-mobile.webp" | "/screenshot-wide.webp" | "/sw.js" | string & {};
	}
}