import { o as head, a as push_element, b as pop_element, i as ensure_array_like, e as escape_html, F as FILENAME } from "../../../../chunks/ui-libs.js";
import { P as PWAInstallPrompt } from "../../../../chunks/PWAInstallPrompt.js";
import { M as Monitor, S as Smartphone, T as Tablet, a as Tv } from "../../../../chunks/tv.js";
import { D as Download } from "../../../../chunks/download.js";
import { W as Wifi } from "../../../../chunks/wifi.js";
import { C as Circle_question_mark } from "../../../../chunks/circle-question-mark.js";
_page[FILENAME] = "src/routes/(app)/device-support/+page.svelte";
function _page($$renderer, $$props) {
  $$renderer.component(
    ($$renderer2) => {
      head("15jn15c", $$renderer2, ($$renderer3) => {
        $$renderer3.title(($$renderer4) => {
          $$renderer4.push(`<title>Device Support - Sephar Studios</title>`);
        });
      });
      PWAInstallPrompt($$renderer2);
      $$renderer2.push(`<!----> <div class="min-h-screen bg-background px-4 py-12">`);
      push_element($$renderer2, "div", 12, 0);
      $$renderer2.push(`<div class="max-w-4xl mx-auto">`);
      push_element($$renderer2, "div", 13, 2);
      $$renderer2.push(`<h1 class="text-3xl font-bold mb-2">`);
      push_element($$renderer2, "h1", 14, 4);
      $$renderer2.push(`Device Support</h1>`);
      pop_element();
      $$renderer2.push(` <p class="text-muted-foreground mb-10">`);
      push_element($$renderer2, "p", 15, 4);
      $$renderer2.push(`Stream Sephar Studios on any screen, anywhere.</p>`);
      pop_element();
      $$renderer2.push(` <section class="mb-12">`);
      push_element($$renderer2, "section", 18, 4);
      $$renderer2.push(`<h2 class="text-xl font-semibold mb-6">`);
      push_element($$renderer2, "h2", 19, 6);
      $$renderer2.push(`Supported Devices</h2>`);
      pop_element();
      $$renderer2.push(` <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">`);
      push_element($$renderer2, "div", 20, 6);
      $$renderer2.push(`<div class="bg-card border border-border rounded-xl p-5 text-center">`);
      push_element($$renderer2, "div", 21, 8);
      Monitor($$renderer2, { class: "w-8 h-8 mx-auto mb-3 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold mb-2">`);
      push_element($$renderer2, "h3", 23, 10);
      $$renderer2.push(`Desktop &amp; Laptop</h3>`);
      pop_element();
      $$renderer2.push(` <ul class="text-sm text-muted-foreground space-y-1">`);
      push_element($$renderer2, "ul", 24, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 25, 12);
      $$renderer2.push(`Chrome 90+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 26, 12);
      $$renderer2.push(`Firefox 88+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 27, 12);
      $$renderer2.push(`Safari 14+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 28, 12);
      $$renderer2.push(`Edge 90+</li>`);
      pop_element();
      $$renderer2.push(`</ul>`);
      pop_element();
      $$renderer2.push(` <p class="text-xs text-green-400 mt-3">`);
      push_element($$renderer2, "p", 30, 10);
      $$renderer2.push(`Full support</p>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5 text-center">`);
      push_element($$renderer2, "div", 32, 8);
      Smartphone($$renderer2, { class: "w-8 h-8 mx-auto mb-3 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold mb-2">`);
      push_element($$renderer2, "h3", 34, 10);
      $$renderer2.push(`Mobile</h3>`);
      pop_element();
      $$renderer2.push(` <ul class="text-sm text-muted-foreground space-y-1">`);
      push_element($$renderer2, "ul", 35, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 36, 12);
      $$renderer2.push(`iOS Safari 14+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 37, 12);
      $$renderer2.push(`Android Chrome 90+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 38, 12);
      $$renderer2.push(`Samsung Internet 14+</li>`);
      pop_element();
      $$renderer2.push(`</ul>`);
      pop_element();
      $$renderer2.push(` <p class="text-xs text-green-400 mt-3">`);
      push_element($$renderer2, "p", 40, 10);
      $$renderer2.push(`Full support + PWA</p>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5 text-center">`);
      push_element($$renderer2, "div", 42, 8);
      Tablet($$renderer2, { class: "w-8 h-8 mx-auto mb-3 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold mb-2">`);
      push_element($$renderer2, "h3", 44, 10);
      $$renderer2.push(`Tablet</h3>`);
      pop_element();
      $$renderer2.push(` <ul class="text-sm text-muted-foreground space-y-1">`);
      push_element($$renderer2, "ul", 45, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 46, 12);
      $$renderer2.push(`iPad (iOS 14+)</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 47, 12);
      $$renderer2.push(`Android tablets</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 48, 12);
      $$renderer2.push(`Surface (Edge)</li>`);
      pop_element();
      $$renderer2.push(`</ul>`);
      pop_element();
      $$renderer2.push(` <p class="text-xs text-green-400 mt-3">`);
      push_element($$renderer2, "p", 50, 10);
      $$renderer2.push(`Full support + PWA</p>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5 text-center">`);
      push_element($$renderer2, "div", 52, 8);
      Tv($$renderer2, { class: "w-8 h-8 mx-auto mb-3 text-muted-foreground" });
      $$renderer2.push(`<!----> <h3 class="font-semibold mb-2">`);
      push_element($$renderer2, "h3", 54, 10);
      $$renderer2.push(`Smart TV</h3>`);
      pop_element();
      $$renderer2.push(` <ul class="text-sm text-muted-foreground space-y-1">`);
      push_element($$renderer2, "ul", 55, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 56, 12);
      $$renderer2.push(`Samsung Tizen 5+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 57, 12);
      $$renderer2.push(`LG webOS 5+</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 58, 12);
      $$renderer2.push(`Android TV</li>`);
      pop_element();
      $$renderer2.push(`</ul>`);
      pop_element();
      $$renderer2.push(` <p class="text-xs text-yellow-400 mt-3">`);
      push_element($$renderer2, "p", 60, 10);
      $$renderer2.push(`Browser-based</p>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</section>`);
      pop_element();
      $$renderer2.push(` <section class="mb-12">`);
      push_element($$renderer2, "section", 66, 4);
      $$renderer2.push(`<h2 class="text-xl font-semibold mb-4">`);
      push_element($$renderer2, "h2", 67, 6);
      $$renderer2.push(`Minimum Requirements</h2>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl overflow-hidden">`);
      push_element($$renderer2, "div", 68, 6);
      $$renderer2.push(`<table class="w-full text-sm">`);
      push_element($$renderer2, "table", 69, 8);
      $$renderer2.push(`<thead class="bg-muted/30">`);
      push_element($$renderer2, "thead", 70, 10);
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 71, 12);
      $$renderer2.push(`<th class="text-left px-4 py-3 text-muted-foreground font-medium">`);
      push_element($$renderer2, "th", 72, 14);
      $$renderer2.push(`Feature</th>`);
      pop_element();
      $$renderer2.push(`<th class="text-left px-4 py-3 text-muted-foreground font-medium">`);
      push_element($$renderer2, "th", 73, 14);
      $$renderer2.push(`Requirement</th>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`</thead>`);
      pop_element();
      $$renderer2.push(`<tbody class="divide-y divide-border">`);
      push_element($$renderer2, "tbody", 76, 10);
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 77, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 77, 16);
      $$renderer2.push(`Internet speed (SD)</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 77, 62);
      $$renderer2.push(`3 Mbps</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 78, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 78, 16);
      $$renderer2.push(`Internet speed (HD)</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 78, 62);
      $$renderer2.push(`5 Mbps</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 79, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 79, 16);
      $$renderer2.push(`Internet speed (4K)</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 79, 62);
      $$renderer2.push(`25 Mbps</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 80, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 80, 16);
      $$renderer2.push(`RAM (mobile)</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 80, 55);
      $$renderer2.push(`2 GB</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 81, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 81, 16);
      $$renderer2.push(`Storage for downloads</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 81, 64);
      $$renderer2.push(`1 GB free (varies by content)</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 82, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 82, 16);
      $$renderer2.push(`JavaScript</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 82, 53);
      $$renderer2.push(`Must be enabled</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`<tr>`);
      push_element($$renderer2, "tr", 83, 12);
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 83, 16);
      $$renderer2.push(`Cookies</td>`);
      pop_element();
      $$renderer2.push(`<td class="px-4 py-3">`);
      push_element($$renderer2, "td", 83, 50);
      $$renderer2.push(`Must be enabled</td>`);
      pop_element();
      $$renderer2.push(`</tr>`);
      pop_element();
      $$renderer2.push(`</tbody>`);
      pop_element();
      $$renderer2.push(`</table>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</section>`);
      pop_element();
      $$renderer2.push(` <section class="mb-12" id="install">`);
      push_element($$renderer2, "section", 90, 4);
      $$renderer2.push(`<h2 class="text-xl font-semibold mb-2">`);
      push_element($$renderer2, "h2", 91, 6);
      $$renderer2.push(`Install the App</h2>`);
      pop_element();
      $$renderer2.push(` <p class="text-muted-foreground text-sm mb-6">`);
      push_element($$renderer2, "p", 92, 6);
      $$renderer2.push(`Sephar Studios is a Progressive Web App — install it on your device for the best experience,
        offline access, and a native app feel with no app store required.</p>`);
      pop_element();
      $$renderer2.push(` <div class="grid grid-cols-1 md:grid-cols-2 gap-4">`);
      push_element($$renderer2, "div", 97, 6);
      $$renderer2.push(`<div class="bg-card border border-border rounded-xl p-5">`);
      push_element($$renderer2, "div", 99, 8);
      $$renderer2.push(`<div class="flex items-center gap-2 mb-3">`);
      push_element($$renderer2, "div", 100, 10);
      Download($$renderer2, { class: "w-4 h-4 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold text-sm">`);
      push_element($$renderer2, "h3", 102, 12);
      $$renderer2.push(`Android (Chrome)</h3>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <ol class="text-sm text-muted-foreground space-y-2 list-decimal list-inside">`);
      push_element($$renderer2, "ol", 104, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 105, 12);
      $$renderer2.push(`Open Sephar Studios in Chrome</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 106, 12);
      $$renderer2.push(`Tap the 3-dot menu in the top right</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 107, 12);
      $$renderer2.push(`Tap "Add to Home screen"</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 108, 12);
      $$renderer2.push(`Tap "Add" to confirm</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 109, 12);
      $$renderer2.push(`The app icon appears on your home screen</li>`);
      pop_element();
      $$renderer2.push(`</ol>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5">`);
      push_element($$renderer2, "div", 114, 8);
      $$renderer2.push(`<div class="flex items-center gap-2 mb-3">`);
      push_element($$renderer2, "div", 115, 10);
      Download($$renderer2, { class: "w-4 h-4 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold text-sm">`);
      push_element($$renderer2, "h3", 117, 12);
      $$renderer2.push(`iPhone / iPad (Safari)</h3>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <ol class="text-sm text-muted-foreground space-y-2 list-decimal list-inside">`);
      push_element($$renderer2, "ol", 119, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 120, 12);
      $$renderer2.push(`Open Sephar Studios in Safari</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 121, 12);
      $$renderer2.push(`Tap the Share button (rectangle with arrow)</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 122, 12);
      $$renderer2.push(`Scroll down and tap "Add to Home Screen"</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 123, 12);
      $$renderer2.push(`Tap "Add" to confirm</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 124, 12);
      $$renderer2.push(`The app icon appears on your home screen</li>`);
      pop_element();
      $$renderer2.push(`</ol>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5">`);
      push_element($$renderer2, "div", 129, 8);
      $$renderer2.push(`<div class="flex items-center gap-2 mb-3">`);
      push_element($$renderer2, "div", 130, 10);
      Download($$renderer2, { class: "w-4 h-4 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold text-sm">`);
      push_element($$renderer2, "h3", 132, 12);
      $$renderer2.push(`Desktop (Chrome / Edge)</h3>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <ol class="text-sm text-muted-foreground space-y-2 list-decimal list-inside">`);
      push_element($$renderer2, "ol", 134, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 135, 12);
      $$renderer2.push(`Open Sephar Studios in Chrome or Edge</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 136, 12);
      $$renderer2.push(`Look for the install icon in the address bar</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 137, 12);
      $$renderer2.push(`Click it and select "Install"</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 138, 12);
      $$renderer2.push(`The app opens in its own window</li>`);
      pop_element();
      $$renderer2.push(`</ol>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <div class="bg-card border border-border rounded-xl p-5">`);
      push_element($$renderer2, "div", 143, 8);
      $$renderer2.push(`<div class="flex items-center gap-2 mb-3">`);
      push_element($$renderer2, "div", 144, 10);
      Wifi($$renderer2, { class: "w-4 h-4 text-primary" });
      $$renderer2.push(`<!----> <h3 class="font-semibold text-sm">`);
      push_element($$renderer2, "h3", 146, 12);
      $$renderer2.push(`Offline Downloads (Premium+)</h3>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(` <ol class="text-sm text-muted-foreground space-y-2 list-decimal list-inside">`);
      push_element($$renderer2, "ol", 148, 10);
      $$renderer2.push(`<li>`);
      push_element($$renderer2, "li", 149, 12);
      $$renderer2.push(`Install the app on your device</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 150, 12);
      $$renderer2.push(`Browse to any movie or episode</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 151, 12);
      $$renderer2.push(`Tap the download icon to save offline</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 152, 12);
      $$renderer2.push(`Go to your Downloads section</li>`);
      pop_element();
      $$renderer2.push(` <li>`);
      push_element($$renderer2, "li", 153, 12);
      $$renderer2.push(`Watch without internet</li>`);
      pop_element();
      $$renderer2.push(`</ol>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</section>`);
      pop_element();
      $$renderer2.push(` <section>`);
      push_element($$renderer2, "section", 160, 4);
      $$renderer2.push(`<h2 class="text-xl font-semibold mb-4 flex items-center gap-2">`);
      push_element($$renderer2, "h2", 161, 6);
      Circle_question_mark($$renderer2, { class: "w-5 h-5 text-muted-foreground" });
      $$renderer2.push(`<!----> Troubleshooting</h2>`);
      pop_element();
      $$renderer2.push(` <div class="space-y-3">`);
      push_element($$renderer2, "div", 165, 6);
      $$renderer2.push(`<!--[-->`);
      const each_array = ensure_array_like([
        {
          q: "Video won't play or keeps buffering",
          a: "Check your internet speed. Try switching to a lower quality in the player settings. Reload the page. Clear your browser cache."
        },
        {
          q: "Downloads not working",
          a: "Downloads require Premium or Creator plan. Make sure you have enough storage space. Downloads require the app to be installed as a PWA."
        },
        {
          q: "Can't connect wallet",
          a: "Make sure MetaMask or your Web3 wallet is installed and unlocked. Switch to the Polygon Amoy network. Refresh the page after connecting."
        },
        {
          q: "Kids content showing adult content",
          a: "Set up Parental Controls under Settings. Ensure your child's profile is set to Kids type. Enable Safe Exploration Mode."
        },
        {
          q: "App not installable",
          a: "Make sure you're using a supported browser (Chrome, Edge, Safari). The install prompt appears automatically on supported devices. Try refreshing the page."
        }
      ]);
      for (let $$index = 0, $$length = each_array.length; $$index < $$length; $$index++) {
        let item = each_array[$$index];
        $$renderer2.push(`<details class="bg-card border border-border rounded-xl group">`);
        push_element($$renderer2, "details", 173, 10);
        $$renderer2.push(`<summary class="px-5 py-4 cursor-pointer text-sm font-medium flex items-center justify-between list-none">`);
        push_element($$renderer2, "summary", 174, 12);
        $$renderer2.push(`${escape_html(item.q)} <span class="text-muted-foreground text-xs group-open:rotate-180 transition-transform">`);
        push_element($$renderer2, "span", 176, 14);
        $$renderer2.push(`▼</span>`);
        pop_element();
        $$renderer2.push(`</summary>`);
        pop_element();
        $$renderer2.push(` <div class="px-5 pb-4 text-sm text-muted-foreground">`);
        push_element($$renderer2, "div", 178, 12);
        $$renderer2.push(`${escape_html(item.a)}</div>`);
        pop_element();
        $$renderer2.push(`</details>`);
        pop_element();
      }
      $$renderer2.push(`<!--]--></div>`);
      pop_element();
      $$renderer2.push(`</section>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
      $$renderer2.push(`</div>`);
      pop_element();
    },
    _page
  );
}
_page.render = function() {
  throw new Error("Component.render(...) is no longer valid in Svelte 5. See https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes for more information");
};
export {
  _page as default
};
